module.exports = {
    resource: '/',
    path: '/',
    httpMethod: 'GET',
    headers:
    {
        Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        'Accept-Encoding': 'gzip, deflate, br',
        'Accept-Language': 'en-US,en;q=0.9',
        'CloudFront-Forwarded-Proto': 'https',
        'CloudFront-Is-Desktop-Viewer': 'true',
        'CloudFront-Is-Mobile-Viewer': 'false',
        'CloudFront-Is-SmartTV-Viewer': 'false',
        'CloudFront-Is-Tablet-Viewer': 'false',
        'CloudFront-Viewer-Country': 'US',
        Host: 'adqsv1eqy0.execute-api.us-east-1.amazonaws.com',
        Referer: 'https://console.aws.amazon.com/apigateway/home?region=us-east-1',
        'upgrade-insecure-requests': '1',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
        Via: '2.0 29f7f51088f787614ba16c3961f39f43.cloudfront.net (CloudFront)',
        'X-Amz-Cf-Id': 'P2OfaOzlNJAWV9Gn1ExsmqY3LkTzMLrOWY2iBJnjMTIaeYHLhXkIaA==',
        'X-Amzn-Trace-Id': 'Root=1-5abdd2eb-aec7087d396f350db0622907',
        'X-Forwarded-For': '173.217.218.42, 52.46.21.12',
        'X-Forwarded-Port': '443',
        'X-Forwarded-Proto': 'https'
    },
    queryStringParameters: null,
    pathParameters: null,
    stageVariables: null,
    requestContext: {
        resourceId: 'yz0s2h86oe',
        resourcePath: '/',
        httpMethod: 'GET',
        extendedRequestId: 'Ei3k3H20oAMF4IA=',
        requestTime: '30/Mar/2018:06:02:19 +0000',
        path: '/dev',
        accountId: '616385475223',
        protocol: 'HTTP/1.1',
        stage: 'dev',
        requestTimeEpoch: 1522389739917,
        requestId: 'e81454ba-33df-11e8-b088-696110ae5d1c',
        identity: {
            cognitoIdentityPoolId: null,
            accountId: null,
            cognitoIdentityId: null,
            caller: null,
            sourceIp: '173.217.218.42',
            accessKey: null,
            cognitoAuthenticationType: null,
            cognitoAuthenticationProvider: null,
            userArn: null,
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
            user: null
        },
        apiId: 'adqsv1eqy0'
    },
    body: null,
    isBase64Encoded: false
}